[Interface]
PrivateKey = aAl7UiUuFtgybdIl9FqJeMA0/Hl5mCt0OPfuim8nfFo=
Address = 172.16.21.7/32
DNS = 1.1.1.1

[Peer]
PublicKey = S3EUCC1nzDjFp9bxXoPQoJSBCxCAU/NuO1azvnZihW4=
Endpoint = 103.93.129.13:51281
AllowedIPs = 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12
PersistentKeepalive = 15
